apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cic-ingress
spec:
  rules:
    - host: cic.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cic-gateway
                port:
                  number: 80
