apiVersion: apps/v1
kind: Deployment
metadata:
  name: cic-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cic-api
  template:
    metadata:
      labels:
        app: cic-api
    spec:
      containers:
        - name: cic-api
          image: cic-api:latest
          ports:
            - containerPort: 8080
