apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-v3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harness-v3
  template:
    metadata:
      labels:
        app: harness-v3
    spec:
      containers:
        - name: harness
          image: harness-v3:latest
