import os
import sys
import re
import shutil
import argparse

ROOT_DIR = "C:/dev"
DOCS_DIR = os.path.join(ROOT_DIR, "docs").replace("\\", "/")

# Distinct exit codes per step
EXIT_CODES = {
    "check": 1,
    "rename": 2,
    "copy_vaults": 3,
    "create_stubs": 4,
    "fix_file_urls": 5,
    "fix_relative_paths": 6
}

# Standard Stub List based on current mkdocs warnings
REQUIRED_STUBS = [
    "docs/operations/runbook.md",
    "docs/api/autonomy.md",
    "docs/meta/cic-os-doc-unification-2026-07-03.md",
    "docs/cic-system.md",
    "docs/rewrite-labs-system.md",
    "docs/reference/architecture.md",
    "docs/autonomy-model.md"
]

# Vault folders to sync
VAULT_DIRS = {
    "cic-ref": os.path.join(ROOT_DIR, "cic-ref").replace("\\", "/"),
    "rl-ref": os.path.join(ROOT_DIR, "rl-ref").replace("\\", "/")
}

# Naming convention rename list
RENAMES = {
    "docs/KB-OPERATIONS.md": "docs/kb-operations.md",
    "docs/meta/BROKEN-LINKS-ACTION-PLAN.md": "docs/meta/broken-links-action-plan.md"
}

def normalize_path(p):
    return p.replace("\\", "/").strip()

def get_relative_depth_prefix(file_path):
    # Calculates relative prefix (e.g. "../" or "../../") to go from file_path back to docs/ root
    rel_from_docs = os.path.relpath(DOCS_DIR, os.path.dirname(file_path))
    prefix = normalize_path(rel_from_docs)
    if prefix == ".":
        return ""
    return prefix + "/"

def copy_vaults(dry_run=False):
    print("=== Copying Vaults ===")
    banner = (
        "> [!WARNING]\n"
        "> This file is autogenerated from the root vault source. Any manual changes made to this file will be overwritten on the next sync.\n\n"
    )
    for vault_name, src_dir in VAULT_DIRS.items():
        if not os.path.lexists(src_dir):
            print(f"Vault source directory {src_dir} does not exist. Skipping.")
            continue
        
        dest_dir = os.path.join(DOCS_DIR, vault_name).replace("\\", "/")
        if not dry_run and not os.path.lexists(dest_dir):
            os.makedirs(dest_dir)
            
        for file_name in os.listdir(src_dir):
            if not file_name.endswith(".md"):
                continue
            src_file = os.path.join(src_dir, file_name).replace("\\", "/")
            dest_file = os.path.join(dest_dir, file_name).replace("\\", "/")
            
            print(f"Copying vault file: {vault_name}/{file_name}")
            if not dry_run:
                try:
                    with open(src_file, "r", encoding="utf-8") as f:
                        content = f.read()
                    # Prepend warning banner
                    with open(dest_file, "w", encoding="utf-8") as f:
                        f.write(banner + content)
                except Exception as e:
                    print(f"Error copying {src_file}: {e}")
                    sys.exit(EXIT_CODES["copy_vaults"])

def create_stubs(dry_run=False):
    print("=== Creating Stubs ===")
    for stub_rel in REQUIRED_STUBS:
        stub_path = os.path.join(ROOT_DIR, stub_rel).replace("\\", "/")
        if os.path.lexists(stub_path):
            print(f"Stub file already exists: {stub_rel}. Skipping.")
            continue
            
        print(f"Creating stub: {stub_rel}")
        if not dry_run:
            dest_dir = os.path.dirname(stub_path)
            if not os.path.lexists(dest_dir):
                os.makedirs(dest_dir)
                
            prefix = get_relative_depth_prefix(stub_path)
            title = os.path.basename(stub_path).replace(".md", "").replace("-", " ").title()
            
            stub_content = (
                f"# {title}\n\n"
                f"[Back to index]({prefix}index-unified.md)\n\n"
                f"> [!NOTE]\n"
                f"> This is a placeholder stub for proposed documentation. Full content will be integrated during phase execution.\n\n"
                f"*For more details on the roadmap, see the [Unified Roadmap]({prefix}roadmaps/unified-roadmap.md).*\n"
            )
            try:
                with open(stub_path, "w", encoding="utf-8") as f:
                    f.write(stub_content)
            except Exception as e:
                print(f"Error creating stub {stub_path}: {e}")
                sys.exit(EXIT_CODES["create_stubs"])

def fix_file_urls(dry_run=False):
    print("=== Fixing file:/// URLs ===")
    # Matches markdown links with file:/// (compiled with DOTALL for Windows CRLF consistency)
    link_regex = re.compile(r"\[([^\]]*)\]\((file:///([^)]*))\)", re.IGNORECASE | re.DOTALL)
    
    for root, _, files in os.walk(DOCS_DIR):
        for file in files:
            if not file.endswith(".md"):
                continue
            file_path = os.path.join(root, file).replace("\\", "/")
            
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    content = f.read()
            except Exception as e:
                print(f"Error reading {file_path}: {e}")
                continue
                
            modified = False
            new_content = content
            
            # Find all file:/// links
            for match in link_regex.finditer(content):
                full_match = match.group(0)
                text = match.group(1)
                absolute_path = normalize_path(match.group(3)) # normalize path backslashes/spaces
                
                clean_abs = absolute_path
                # Remove leading slash if it starts with /C:/dev
                if clean_abs.startswith("/"):
                    clean_abs = clean_abs[1:]
                    
                # Correctly resolve path to be relative to the root dev/ workspace folder
                if clean_abs.lower().startswith("c:/dev/"):
                    clean_abs = clean_abs[7:]
                elif clean_abs.lower().startswith("c:/dev"):
                    clean_abs = clean_abs[6:]
                else:
                    if re.match(r"^[a-zA-Z]:", clean_abs):
                        clean_abs = clean_abs[2:]
                    if clean_abs.startswith("/"):
                        clean_abs = clean_abs[1:]
                
                abs_target = os.path.join(ROOT_DIR, clean_abs).replace("\\", "/")
                rel_target = os.path.relpath(abs_target, os.path.dirname(file_path)).replace("\\", "/")
                
                replacement = f"[{text}]({rel_target})"
                print(f"File {os.path.basename(file_path)}: replace {full_match} -> {replacement}")
                new_content = new_content.replace(full_match, replacement)
                modified = True
                
            if modified and not dry_run:
                try:
                    with open(file_path, "w", encoding="utf-8") as f:
                        f.write(new_content)
                except Exception as e:
                    print(f"Error writing {file_path}: {e}")
                    sys.exit(EXIT_CODES["fix_file_urls"])

def fix_relative_paths(dry_run=False):
    print("=== Fixing Relative Paths and Backslashes ===")
    # Resolve Windows backslash issues in links
    link_regex = re.compile(r"\[([^\]]*)\]\(([^)]*)\)", re.DOTALL)
    
    for root, _, files in os.walk(DOCS_DIR):
        for file in files:
            if not file.endswith(".md"):
                continue
            file_path = os.path.join(root, file).replace("\\", "/")
            
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    content = f.read()
            except Exception as e:
                print(f"Error reading {file_path}: {e}")
                continue
                
            modified = False
            new_content = content
            
            # Find all links
            for match in link_regex.finditer(content):
                full_match = match.group(0)
                text = match.group(1)
                target = match.group(2).strip()
                
                if target.startswith("http://") or target.startswith("https://") or target.startswith("mailto:") or target.startswith("#"):
                    continue
                
                # 1. Backslash check
                if "\\" in target:
                    fixed_target = normalize_path(target)
                    replacement = f"[{text}]({fixed_target})"
                    print(f"File {os.path.basename(file_path)}: fix slashes {full_match} -> {replacement}")
                    new_content = new_content.replace(full_match, replacement)
                    modified = True
                    target = fixed_target
                
                # 2. Out of bounds relative traversal fix
                if target.startswith("../../docs/"):
                    fixed_target = target.replace("../../docs/", "../")
                    replacement = f"[{text}]({fixed_target})"
                    print(f"File {os.path.basename(file_path)}: fix docs traverse {full_match} -> {replacement}")
                    new_content = new_content.replace(full_match, replacement)
                    modified = True
                    target = fixed_target
                elif target.startswith("../../../cic-ref/"):
                    fixed_target = target.replace("../../../cic-ref/", "../cic-ref/")
                    replacement = f"[{text}]({fixed_target})"
                    print(f"File {os.path.basename(file_path)}: fix vault traverse {full_match} -> {replacement}")
                    new_content = new_content.replace(full_match, replacement)
                    modified = True
                    target = fixed_target
                elif target == "../index-unified.md":
                    fixed_target = "index-unified.md"
                    replacement = f"[{text}]({fixed_target})"
                    print(f"File {os.path.basename(file_path)}: fix self index {full_match} -> {replacement}")
                    new_content = new_content.replace(full_match, replacement)
                    modified = True
                    target = fixed_target
                    
            if modified and not dry_run:
                try:
                    with open(file_path, "w", encoding="utf-8") as f:
                        f.write(new_content)
                except Exception as e:
                    print(f"Error writing {file_path}: {e}")
                    sys.exit(EXIT_CODES["fix_relative_paths"])

def rename_files(dry_run=False):
    print("=== Renaming Files ===")
    for old_rel, new_rel in RENAMES.items():
        old_path = os.path.join(ROOT_DIR, old_rel).replace("\\", "/")
        new_path = os.path.join(ROOT_DIR, new_rel).replace("\\", "/")
        
        if not os.path.lexists(old_path):
            print(f"File to rename does not exist: {old_rel}. Skipping.")
            continue
            
        print(f"Renaming: {old_rel} -> {new_rel}")
        if not dry_run:
            try:
                os.rename(old_path, new_path)
            except Exception as e:
                print(f"Error renaming {old_path}: {e}")
                sys.exit(EXIT_CODES["rename"])
                
        # Update references in all markdown files and mkdocs.yml
        old_name = os.path.basename(old_path)
        new_name = os.path.basename(new_path)
        
        # 1. Update references in docs
        for root, _, files in os.walk(DOCS_DIR):
            for file in files:
                if not file.endswith(".md"):
                    continue
                file_path = os.path.join(root, file).replace("\\", "/")
                
                try:
                    with open(file_path, "r", encoding="utf-8") as f:
                        content = f.read()
                except Exception as e:
                    continue
                    
                if old_name in content:
                    new_content = content.replace(old_name, new_name)
                    print(f"Updating reference in {os.path.basename(file_path)}: {old_name} -> {new_name}")
                    if not dry_run:
                        with open(file_path, "w", encoding="utf-8") as f:
                            f.write(new_content)
                            
        # 2. Update mkdocs.yml
        mkdocs_path = os.path.join(ROOT_DIR, "mkdocs.yml").replace("\\", "/")
        if os.path.lexists(mkdocs_path):
            try:
                with open(mkdocs_path, "r", encoding="utf-8") as f:
                    content = f.read()
                old_yml_rel = old_rel.replace("docs/", "")
                new_yml_rel = new_rel.replace("docs/", "")
                if old_yml_rel in content:
                    new_content = content.replace(old_yml_rel, new_yml_rel)
                    print(f"Updating reference in mkdocs.yml: {old_yml_rel} -> {new_yml_rel}")
                    if not dry_run:
                        with open(mkdocs_path, "w", encoding="utf-8") as f:
                            f.write(new_content)
            except Exception as e:
                print(f"Error updating mkdocs.yml: {e}")

def check_links():
    print("=== Verifying Links (file_exists check) ===")
    link_regex = re.compile(r"\[([^\]]*)\]\(([^)]*)\)", re.DOTALL)
    code_block_regex = re.compile(r"```[\s\S]*?```|`[^`\n]+`", re.DOTALL)
    
    broken_count = 0
    total_internal = 0
    total_external_skipped = 0
    
    for root, _, files in os.walk(DOCS_DIR):
        for file in files:
            if not file.endswith(".md"):
                continue
            file_path = os.path.join(root, file).replace("\\", "/")
            
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    content = f.read()
            except Exception as e:
                print(f"Error reading {file_path}: {e}")
                continue
                
            # Find the index spans of all code blocks to filter links inside them
            code_spans = []
            for cb in code_block_regex.finditer(content):
                code_spans.append(cb.span())
            
            def is_in_code_block(start_idx):
                for start, end in code_spans:
                    if start <= start_idx < end:
                        return True
                return False

            for match in link_regex.finditer(content):
                # Skip link if its match location falls inside a code block
                if is_in_code_block(match.start()):
                    continue
                
                target = match.group(2).strip()
                
                # Filter external links, anchors, and mailtos
                if target.startswith("http://") or target.startswith("https://") or target.startswith("mailto:") or target.startswith("#"):
                    total_external_skipped += 1
                    continue
                
                total_internal += 1
                
                # Split target from anchor if present
                clean_target = normalize_path(target.split("#")[0])
                if not clean_target:
                    continue # Anchor only link, skip check
                
                # Resolve relative path
                if clean_target.lower().startswith("file:///"):
                    local_target = clean_target[8:]
                    if local_target.startswith("/"):
                        local_target = local_target[1:]
                    
                    if local_target.lower().startswith("c:/dev/"):
                        local_target = local_target[7:]
                    elif local_target.lower().startswith("c:/dev"):
                        local_target = local_target[6:]
                    else:
                        if re.match(r"^[a-zA-Z]:", local_target):
                            local_target = local_target[2:]
                        if local_target.startswith("/"):
                            local_target = local_target[1:]
                            
                    resolved_path = os.path.join(ROOT_DIR, local_target).replace("\\", "/")
                else:
                    resolved_path = os.path.normpath(os.path.join(os.path.dirname(file_path), clean_target)).replace("\\", "/")
                
                resolved_path = resolved_path.replace("\\", "/")
                
                # Verify existence using os.path.lexists() to correctly handle symlinks
                if not os.path.lexists(resolved_path):
                    print(f"[ERROR] Broken link in {os.path.relpath(file_path, ROOT_DIR).replace('\\', '/')}: '{target}' (resolved to '{os.path.relpath(resolved_path, ROOT_DIR).replace('\\', '/')}')")
                    broken_count += 1
                    
    print(f"Link check summary: {total_internal} internal links analyzed, {total_external_skipped} external links skipped, {broken_count} broken links detected.")
    if broken_count > 0:
        sys.exit(EXIT_CODES["check"])
    else:
        print("[SUCCESS] All links are valid (physical target files exist on disk)!")

def main():
    parser = argparse.ArgumentParser(description="Deterministic Document Link Fix & Vault Sync Reorganization")
    parser.add_argument("--copy-vaults", action="store_true", help="Sync root vaults to docs/")
    parser.add_argument("--create-stubs", action="store_true", help="Generate missing placeholder stubs")
    parser.add_argument("--fix-file-urls", action="store_true", help="Fix file:/// absolute URLs")
    parser.add_argument("--fix-relative-paths", action="store_true", help="Normalize slashes and relative depths")
    parser.add_argument("--rename-files", action="store_true", help="Perform case renames and update references")
    parser.add_argument("--check", action="store_true", help="Validate file existence for all links")
    parser.add_argument("--all", action="store_true", help="Execute all steps in order")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without writing to disk")
    
    args = parser.parse_args()
    
    if not any([args.copy_vaults, args.create_stubs, args.fix_file_urls, args.fix_relative_paths, args.rename_files, args.check, args.all]):
        parser.print_help()
        sys.exit(0)
        
    dry_run = args.dry_run
    if dry_run:
        print("!!! DRY-RUN MODE ENABLED (No changes will be written to disk) !!!\n")
        
    if args.all or args.copy_vaults:
        copy_vaults(dry_run)
    if args.all or args.create_stubs:
        create_stubs(dry_run)
    if args.all or args.fix_file_urls:
        fix_file_urls(dry_run)
    if args.all or args.fix_relative_paths:
        fix_relative_paths(dry_run)
    if args.all or args.rename_files:
        rename_files(dry_run)
    if args.all or args.check:
        check_links()

if __name__ == "__main__":
    main()
